### ISSUE TITLE
Switch state after first read

### ISSUE THREAD

**Issue by Scratch-net** [mimoo/GoKangarooTwelve#1]
```
	hash := K12.NewK12(nil)
	buf := make([]byte, 32)
	hash.Write(buf)
	hash.Read(buf)
	hash.Read(buf)

```
causes panic because sponge thinks we are still **spongeAbsorbing**

**Comment by mimoo** [comment]
Awesome, thanks for pointing that out! Do you want to submit a PR to fix this?

**Comment by Scratch-net** [comment]
Sure, done

**Comment by mimoo** [comment]
see https://github.com/mimoo/GoKangarooTwelve/pull/2
