### ISSUE TITLE
Not an issue but more of a general question

### ISSUE THREAD

**Issue by MaxflowO2** [mimoo/GoKangarooTwelve#4]
In the example of K12Sum...

Is there a way we can do a K12-256/512 and whatever flavors of the world?

If so, I can probably write that and push you the information.
just wanted to know if hash.Read(out) being []byte, 32 was the 256 edition...

**Comment by mimoo** [comment]
Sorry not sure I understand, there is only one K12 as far as I know

**Comment by MaxflowO2** [comment]
Keep getting this error...

cannot slice hash (type K12.treeState)

was going through your code, how would i get 32/64 bytes for output?

**Comment by mimoo** [comment]
Did you follow the example in the README: https://github.com/mimoo/GoKangarooTwelve#usage ?

Basically you'd have to change this to 64:

```go
  // we squeeze a 32 output
  out := make([]byte, 32)
  hash.Read(out)
```

**Comment by MaxflowO2** [comment]
Thank you, i knew i was forgetting something, and this was it!

I feel dumb, but not so much anymore.
